umd-lib/umd-lib-aspace-theme

frontend/views/layouts/application.html.erb
Browser support check was [dropped in v2.1.0](
https://github.com/archivesspace/archivesspace/commit/2cac094f3b508d472ee3f154cbe3138b46889482)
This removes the call to that partial ( that was removed )
https://issues.umd.edu/browse/LIBASPACE-89
=> LIBASPACE-89 remove call to browser_support partial

public/plugin_init.rb
Redefines the cite_url_and_timestamp method of the Record class to use the EAD location (i.e., handle) as the citation URL. If there is no EAD location for a record, it falls back to the ASpace default of using the PUI URL of the resource.
https://issues.umd.edu/browse/LIBASPACE-121
=> LIBASPACE-121. Use EAD location, if present, as citation URL.

umd_lib_environment_banner_helper.rb
Need to check environment name on the 'short name' ( name before first
dot ), and not the FQDN
https://issues.umd.edu/browse/LIBASPACE-127
=> LIBASPACE-127 Get the short name and not the FQDN for environment name

public/views/layouts/application.html.erb
On the "UMD Header Generator" page
https://umd-header.umd.edu/generator/
used the following values in the fields:
* Include "Make A Gift" Link: Checked
* Make A Gift URL: "https://giving.umd.edu/giving/showSchool.php?name=libraries"
* Inner Wrapper Width, in pixels: 1160
The inner wrapper width was chosen to match the inner wrapper width on
the UMD Libraries home page (http://www.lib.umd.edu/).
In the resulting code, replaced all the "&" characters with "&amp;"
https://issues.umd.edu/browse/LIBASPACE-137
=> LIBASPACE-137. Added "Make a Gift" link to UMD wrapper

public/assets/stylesheets/umd_lib.css, public/locales/en.yml
Overrode "actions.search_in" I18N resource from stock ArchivesSpace
using "public/locales/en.yml" file.
Also changed the spacing in the en.yml file to use 2 spaces for
indentation, instead of 4, both to match the style in stock
ArchivesSpace, and Ruby style.
Added CSS to adjust the width of the form group and "Search" textfield
to the full width of the sidebar, so that the placeholder text would
not be truncated.
Note: The change to the "actions.search_in" resource also changes
the HTML title (displayed in a browser tab).
https://issues.umd.edu/browse/LIBASPACE-139
=> LIBASPACE-139. Changed search placeholder to "Search Within Collection"

public/views/search/search_results.html.erb
The filter div was outside of the proper row, so it was appearing at the bottom of the page instead of as a column to the right.
https://issues.umd.edu/browse/LIBASPACE-136
=> LIBASPACE-136. Fixed location of filter sidebar.

public/locales/en.yml
Combined the "actions.search_in" and "actions.hierarch" resources
under a single "actions" parent, as apparently YAML doesn't like
multiple instance of a parent and takes the last one.
https://issues.umd.edu/browse/LIBASPACE-107
=> LIBASPACE-107. Merged "actions" resources under single subtree

public/locales/en.yml
Set home page title to empty string, so only the brand title ("Archival Collections") is use on the home page.
https://issues.umd.edu/browse/LIBASPACE-130
=> LIBASPACE-130. Fix home page title.

public/views/shared/_record_innards.html.erb
Added the "public/views/shared/_record_innards.html.erb" to
"umd-lib-aspace-theme" plugin, and customized so that the "abstract"
field (when available) would be used in preference to the "scopecontext"
field for the "above the fold" description of a resource.
When the "abstract" is used, the "scopecontext" field will be displayed
in the "Additional Description" accordion tab.
https://issues.umd.edu/browse/LIBASPACE-119
=> LIBASPACE-119. Reversed "abstract" and "scopecontext" text in display

public/views/layouts/application.html.erb
Changed the code to verify that the value returned by AppConfig for the
Google Analytics Tag is not nil or empty, before using it to generate
the HTML.
https://issues.umd.edu/browse/LIBASPACE-148
=> LIBASPACE-148. Improved Google Analytics parameter handling

public/locales/en.yml, public/views/shared/_navigation.html.erb
Implemented in the simplest possible way, as it didn't seem like
something that would change often.
Used "help_tab" in I18N en.yml, following the "search_tab" I18N naming.
https://issues.umd.edu/browse/LIBASPACE-120
=> LIBASPACE-120. Added "Help" menu to navigation bar

public/locales/en.yml
On a resource detail page, changed the following:
* In the blue tab bar, changed "Collection Contents" to "Finding Aid View"
* In the blue tab bar, changed "Container Inventory" label to "Box List"
* In the right sidebar, changed "Collection organization" header
(below the "Search" button") to "Navigate the Collection".
https://issues.umd.edu/browse/LIBASPACE-204
=> LIBASPACE-204. Miscellaneous label changes

public/assets/stylesheets/umd_lib.css
Change the "collapse/expand" chevron in the navigation tree to a
"plus" (when collapsed) and "minus" (when expanded).
https://issues.umd.edu/browse/LIBASPACE-205
=> LIBASPACE-205. Change collapse/expand indicators chevron to plus/minus

public/views/shared/_record_innards.html.erb
This moves the External Document section above Notes in the PUI's
collection record view page.
https://issues.umd.edu/browse/LIBASPACE-214
=> LIBASPACE-214 Move External Documents above Notes in the PUI Collection

public/assets/stylesheets/umd_lib.css, public/locales/en.yml, public/views/objects/show.html.erb, public/views/resources/show.html.erb, public/views/shared/_request_instructions.html.erb
Modified request instructions for "collections" objects
so that the instructions are displayed as part of the template, not
via Rails "flash" messages.
Added "public/views/shared/_request_instructions.html.erb" as a view
helper that can be added where needed to display the instructions.
Added the view helper to the "show" templates for "objects" and
"resources", which were copied from the v2.2.2 ArchivesSpace codebase.
Modified CSS to style the request instructions so that it appears
similar to the Rails "informational" flash notices (this will likely
be changed in the future).
Updated the wording for the request instructions as specified in
LIBASPACE-211, and made displayed in bold as specified in LIBASPACE-213.
https://issues.umd.edu/browse/LIBASPACE-210
=> LIBASPACE-210. Request instructions now display consistently

public/assets/stylesheets/umd_lib.css, public/views/shared/_header.html.erb, public/views/shared/_navigation.html.erb, public/views/shared/_navigation_search.html.erb
Modified the search textbox in the navigation bar to match mockup at
https://umd-lib.github.io/mockups/aspace/home-letter.htm,
including RWD behavior.
Moved search textbox and button into separate helper, because it is
added twice in the page for RWD handling. Added a local parameter
"search_box_id" that gets passed into the helper to distinguish
the HTML ids used in the form tags.
https://issues.umd.edu/browse/LIBASPACE-117
=> LIBASPACE-117. Navigation search textbox formatting updates

public/views/shared/_navigation_search.html.erb
This makes the search form always go to the /search rather than scoping the
search to the repository.
https://issues.umd.edu/browse/LIBASPACE-117
=> LIBASPACE-117 Make search go to /search

public/views/repositories/_repository_details.html.erb
Removed an extraneous "Library" form the "Library Details" panel
("Repository Details" panel in stock ArchivesSpace), as the repository
name in the "name" field of the "repository" database table
already includes "Library" (or "Archives").
https://issues.umd.edu/browse/LIBASPACE-276
=> LIBASPACE-276. Removed extraneous "Library" from "Library Details" panel

README.md, frontend/spec/banner_spec.rb, frontend/spec/rails_helper.rb, frontend/spec/spec_helper, umd_lib_environment_banner_helper.rb
Modified the UMDLibEnvironmentBannerHelper to enable the banner to be
controlled via environment variables.
Kept current implementation based on hostname, but enabled it to be
overridden by that environment variables.
https://issues.umd.edu/browse/LIBASPACE-283
=> LIBASPACE-283. Enable environment banner to be controlled via env vars

public/views/shared/_only_facets.html.erb
Replaced "public/views/shared/_only_facets.html.erb" template with version from ArchivesSpace v3.3.1, and the modified as follows to restore UMD customizations:
* Removed "langcode" from the "preferred_facet_order". While this was probably never any intentional choice, this change was made to preserve the existing facet display order (the "langcode" facet is still displayed, it is just displayed after the "preferred" facets).
* The "subjects" (displayed as "Topic" in the GUI) in the facet is skipped (this is the intentional change made in LIBASPACE-152).
https://issues.umd.edu/browse/LIBASPACE-337
=> LIBASPACE-337. Update "_only_facets.html.erb" for ArchivesSpace v3.3.1

public/views/shared/_search.html.erb
Commented out the "+" button in the search form that enables additional search criteria to be added. This functionality is not working as of ArchivesSpace v3.1.1, as this UMD-customized template file has not been updated to the latest version of the template
(see "public/app/views/shared/_search.html.erb").
Updating to the stock ArchivesSpace template (and modifying to support the UMD customizations to the template) will enable the search criteria functionality. However, other UMD customizations of the application cause form field layout issues. We are not prepared at this time to undertake fixing these layout issues, so simply removing the functionality is a stop-gap measure.
https://umd-dit.atlassian.net/browse/LIBASPACE-341
=> LIBASPACE-341. Commented out "+" button in search form

README.md, public/views/layouts/application.html.erb
Added the following web analytics trackers:
* Fathom
* Matomo
* Plausible.io
This was done was part of an evaluation of which analytics tracker we might wish to use in the future.
https://umd-dit.atlassian.net/browse/LIBASPACE-348
=> LIBASPACE-348. Added additional web analytics trackers

README.md, public/views/layouts/application.html.erb
Removed code for including the Google Analytics tracker, and updated the README.md file.
This makes Matomo the only supported web analytics tracker.
https://umd-dit.atlassian.net/browse/LIBASPACE-352
=> LIBASPACE-352. Removed Google Analytics tracker code
